#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H


enum class TokenType{
    INTEGER,FLOAT,STRING,
    BOOL_TRUE,BOOL_FALSE,NONE,
    KEYWORD_PRINT,KEYWORD_IF,KEYWORD_ELSE,KEYWORD_WHILE,KEYWORD_DEF,KEYWORD_RETURN,

    IDENTIFIER,

    OPERATOR_PLUS,OPERATOR_MINUS,OPERATOR_MULTIPLY,OPERATOR_DIVIDE,
    COMP_EQUALS,COMP_NOT_EQUALS,COMP_LESS,COMP_GREATER,COMP_LESS_EQUAL,COMP_GREATER_EQUAL,

    ASSIGN,
    PUNCTUATION_LEFT_PAREN, PUNCTUATION_RIGHT_PAREN,PUNCTUATION_COMMA,PUNCTUATOR_COLON,
    PUNCTUATOR_SEMICOLON,

    INDENT,DEDENT,NEWLINE,
    END_OF_FILE,ERROR
}